#include "veyra/pipeline/LmxxfNrBackend.h"
#include "veyra/Log.h"
#include <algorithm>
#include <array>
#include <format>
namespace veyra::pipeline{namespace{std::string wm(DWORD c){if(!c)return{};char*r=nullptr;DWORD n=FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER|FORMAT_MESSAGE_FROM_SYSTEM|FORMAT_MESSAGE_IGNORE_INSERTS,nullptr,c,0,reinterpret_cast<char*>(&r),0,nullptr);std::string o=n&&r?std::string(r,r+n):std::format("Win32 {}",c);if(r)LocalFree(r);return o;}}
LmxxfNrBackend::~LmxxfNrBackend(){shutdown();}void LmxxfNrBackend::refreshRuntimeError(){if(!api_.GetLastError)return;std::array<char,2048>b{};if(api_.GetLastError(b.data(),uint32_t(b.size()))==LMXXF_NR_OK&&b[0])lastError_=b.data();}bool LmxxfNrBackend::fail(const char*o,int32_t c){lastError_=std::format("{} rc={}",o,c);refreshRuntimeError();return false;}
bool LmxxfNrBackend::initialize(ID3D12Device*d,ID3D12CommandQueue*q,const std::filesystem::path&a){shutdown();auto dll=a/L"LmxxfNrRuntime.dll";module_=LoadLibraryExW(dll.c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);if(!module_){lastError_=wm(GetLastError());return false;}auto g=reinterpret_cast<LmxxfNrGetApiFn>(GetProcAddress(module_,"LmxxfNrGetApi"));if(!g)return false;api_={};api_.struct_size=sizeof(api_);int32_t rc=g(LMXXF_NR_ABI_VERSION,&api_);if(rc==LMXXF_NR_INVALID_ARGUMENT){api_={};api_.struct_size=LMXXF_NR_API_V1_SIZE;rc=g(LMXXF_NR_ABI_VERSION,&api_);}if(rc!=LMXXF_NR_OK||!api_.QueryCapabilities||!api_.Create||!api_.Destroy||!api_.PrepareSession||!api_.PrepareFrame||!api_.RecordInputs||!api_.EnqueueHip||!api_.RecordOutputs||!api_.Retire||!api_.Drain||!api_.GetLastError)return false;capabilities_={};capabilities_.struct_size=sizeof(capabilities_);if(api_.QueryCapabilities(&capabilities_)!=LMXXF_NR_OK)return false;LmxxfNrCreateInfo ci{};ci.struct_size=sizeof(ci);ci.device=d;ci.queue=q;ci.assets_directory=a.c_str();if(api_.Create(&ci,&context_)!=LMXXF_NR_OK||!context_)return false;queue_=q;if(api_.PrepareSession(context_)!=LMXXF_NR_OK)return false;return true;}
bool LmxxfNrBackend::cancelLiveJob(){if(!job_.handle)return true;int32_t rc=api_.CancelUnsubmitted?api_.CancelUnsubmitted(context_,job_.handle):api_.Retire(context_,job_.handle);job_={};return rc==LMXXF_NR_OK;}
bool LmxxfNrBackend::prepareAndRecordInput(ID3D12GraphicsCommandList*l,ID3D12Resource*c,D3D12_RESOURCE_STATES st,uint32_t w,uint32_t h,float strength,uint64_t fid,bool reset){if(!ready()||!l||!c)return false;auto d=c->GetDesc();if(d.Format!=DXGI_FORMAT_R16G16B16A16_FLOAT||d.Width!=w||d.Height!=h)return false;if(reset&&api_.ResetHistory&&api_.ResetHistory(context_)!=LMXXF_NR_OK)return false;LmxxfNrFrameInfo i{};i.struct_size=sizeof(i);i.session_id=sessionId_;i.frame_id=fid?fid:++frameCounter_;i.list_generation=++listGeneration_;i.command_list=l;i.color_width=w;i.color_height=h;i.color=c;i.color_state=uint32_t(st);i.flags=LMXXF_NR_FRAME_FLAG_STRENGTH;i.transfer_strength=std::clamp(strength,0.0f,1.0f);i.color_strength=i.model_scale=i.pre_exposure=i.exposure_scale=1.0f;job_={};job_.struct_size=sizeof(job_);int32_t rc=api_.PrepareFrame(context_,&i,&job_);if(rc!=LMXXF_NR_OK)return fail("PrepareFrame",rc);rc=api_.RecordInputs(context_,job_.handle,l);return rc==LMXXF_NR_OK?true:fail("RecordInputs",rc);}
bool LmxxfNrBackend::recordOutput(ID3D12GraphicsCommandList*l){int32_t rc=api_.RecordOutputs(context_,job_.handle,l);return rc==LMXXF_NR_OK?true:fail("RecordOutputs",rc);}bool LmxxfNrBackend::enqueue(){int32_t rc=api_.EnqueueHip(context_,job_.handle,queue_);return rc==LMXXF_NR_OK?true:fail("EnqueueHip",rc);}bool LmxxfNrBackend::retire(){if(!job_.handle)return true;int32_t rc=api_.Retire(context_,job_.handle);job_={};return rc==LMXXF_NR_OK?true:fail("Retire",rc);}void LmxxfNrBackend::shutdown(){if(context_){if(job_.handle)cancelLiveJob();if(api_.Drain)api_.Drain(context_);if(api_.Destroy)api_.Destroy(context_);context_=nullptr;}if(module_){FreeLibrary(module_);module_=nullptr;}queue_=nullptr;job_={};}}
