# Local FFmpeg finder for Veyra.
# Supports both the original vcpkg prefix and a plain Windows shared-development
# prefix such as Gyan's release full shared package.
include(FindPackageHandleStandardArgs)

set(_VEYRA_FFMPEG_HINT "")
if(DEFINED VEYRA_FFMPEG_ROOT AND VEYRA_FFMPEG_ROOT)
  set(_VEYRA_FFMPEG_HINT "${VEYRA_FFMPEG_ROOT}")
endif()

find_path(FFMPEG_INCLUDE_DIRS
  NAMES libavformat/avformat.h
  HINTS "${_VEYRA_FFMPEG_HINT}/include"
  NO_DEFAULT_PATH)

set(FFMPEG_LIBRARY_DIRS "${_VEYRA_FFMPEG_HINT}/lib")

find_library(FFMPEG_AVFORMAT_LIBRARY NAMES avformat
  HINTS "${FFMPEG_LIBRARY_DIRS}" NO_DEFAULT_PATH)
find_library(FFMPEG_AVCODEC_LIBRARY NAMES avcodec
  HINTS "${FFMPEG_LIBRARY_DIRS}" NO_DEFAULT_PATH)
find_library(FFMPEG_AVUTIL_LIBRARY NAMES avutil
  HINTS "${FFMPEG_LIBRARY_DIRS}" NO_DEFAULT_PATH)
find_library(FFMPEG_SWRESAMPLE_LIBRARY NAMES swresample
  HINTS "${FFMPEG_LIBRARY_DIRS}" NO_DEFAULT_PATH)
find_library(FFMPEG_SWSCALE_LIBRARY NAMES swscale
  HINTS "${FFMPEG_LIBRARY_DIRS}" NO_DEFAULT_PATH)

set(FFMPEG_LIBRARIES
  "${FFMPEG_AVFORMAT_LIBRARY}"
  "${FFMPEG_AVCODEC_LIBRARY}"
  "${FFMPEG_AVUTIL_LIBRARY}"
  "${FFMPEG_SWRESAMPLE_LIBRARY}"
  "${FFMPEG_SWSCALE_LIBRARY}")

find_package_handle_standard_args(FFMPEG
  REQUIRED_VARS
    FFMPEG_INCLUDE_DIRS
    FFMPEG_AVFORMAT_LIBRARY
    FFMPEG_AVCODEC_LIBRARY
    FFMPEG_AVUTIL_LIBRARY
    FFMPEG_SWRESAMPLE_LIBRARY
    FFMPEG_SWSCALE_LIBRARY)

mark_as_advanced(
  FFMPEG_INCLUDE_DIRS
  FFMPEG_AVFORMAT_LIBRARY
  FFMPEG_AVCODEC_LIBRARY
  FFMPEG_AVUTIL_LIBRARY
  FFMPEG_SWRESAMPLE_LIBRARY
  FFMPEG_SWSCALE_LIBRARY)
